import org.apache.tools.ant.filters.ReplaceTokens

group 'com.btk5h.skript-mirror'
version '2.6.3'

def latestJava = 25
def oldestJava = 21

apply plugin: 'java'

/*
repositories {
	mavenCentral()
	maven { url 'https://repo.papermc.io/repository/maven-public/' }
	maven { url 'https://repo.skriptlang.org/releases' }
}
*/

processResources {
	filter ReplaceTokens, tokens: [
		"version": version
	]
}

java {
	toolchain.languageVersion.set(JavaLanguageVersion.of(latestJava))
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.compilerArgs += [
	    '-source', "${oldestJava}",
	    '-target', "${oldestJava}"
	]
}

dependencies {
	compileOnly "io.papermc.paper:paper-api:26.1.2.build.+"
//	compileOnly "com.github.SkriptLang:Skript:2.15.2"
	compileOnly "com.github.SkriptLang:Skript:dev~patch-SNAPSHOT"
}
