rootProject.name = 'skript-reflect'

dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	repositories {
		mavenCentral()
		maven { url 'https://repo.papermc.io/repository/maven-public/' }
		maven { url 'https://repo.skriptlang.org/releases' }
		maven { url 'https://jitpack.io' }
	}
}
