test "CondChange - set":
  assert raw ({_v}) can be set to a string with "a variable should be settable to a string"
  assert raw (location of (random player out of all players)) can't be set to a string with "the location expression shouldn't be settable to a string"
  assert raw (name of {_v}) can be set to a string with "the name expression should be settable to a string"
  assert raw (name of {_v}) can't be set to an integer with "the name expression shouldn't be settable to an integer"
  assert raw (name of {_v}) can't be set to strings with "the name expression shouldn't be settable to multiple strings"
  assert raw ({_v::*}) can be set to strings with "a list variable should be settable to multiple strings"
  assert raw ({_v}) can't be set to strings with "a non-list variable should not be settable to multiple strings"

test "CondChange - reset":
  assert raw (uppercase "") can't be reset with "the uppercase expression shouldn't be resettable"
  assert raw (portal cooldown of {_v}) can be reset with "the portal cooldown expression should be resettable"

test "CondChange - delete":
  assert raw ({_v}) can be deleted with "a variable should be deletable"
  assert raw (uppercase "") can't be deleted with "the uppercase expression shouldn't be deletable"

test "CondChange - add":
  assert an integer can be added to raw ({_v}) with "an integer should be addable to a variable"
  assert integers can be added to raw ({_v}) with "multiple integers should be addable to a variable"
  assert a string can't be added to raw (all players) with "a string shouldn't be addable to all players"

test "CondChange - remove":
  assert a player can be removed from raw ({_v::*}) with "a player should be removable from a variable"
  assert players can be removed from raw ({_v::*}) with "multiple players should be removable from a variable"
  assert a player can't be removed from raw (block at {_v}) with "a player shouldn't be removable the block expression"
  assert a integer can be removed from raw (durability of {_v}) with "an integer should be removable from the durability expression"

test "CondChange - remove all":
  assert all player can be removed from raw ({_v::*}) with "all integer should be removable from a variable"
  assert all players can be removed from raw ({_v::*}) with "all integers should be removable from a variable"
  assert all strings can't be removed from raw (name of {_v}) with "all strings shouldn't be removable from the name expression"
  assert all players can't be removed from raw (name of {_v}) with "all players shouldn't be removable from the name expression"
